import urllib.request
import json

base_url = "https://ngtp-litigation-engine.onrender.com"

# Check PDF availability
endpoints_to_check = [
    "/AICA_Level_2_Capstone_Problem_Statement.pdf",
    "/sample-data/set1-proceed/Set1_Tax_Invoice_Rule46.pdf",
    "/sample-data/set1-proceed/Set1_Bank_RTGS_Statement.pdf",
    "/sample-data/set1-proceed/Set1_EWay_Bill_PartA_B.pdf",
    "/sample-data/set1-proceed/Set1_Weighbridge_FASTag_Receipt.pdf",
    "/sample-data/set1-proceed/Set1_Tax_Ledger_GSTR1_Ack.pdf",
    "/sample-data/set1-proceed/Set1_Impugned_DRC07_Order.pdf",
    "/sample-data/set1-proceed/Set1_Statement_of_Facts_and_Grounds.txt",
    "/sample-data/set2-hold/Set2_Tax_Invoice_Deficient.pdf",
    "/sample-data/set2-hold/Set2_Bank_Statement_Delayed.pdf",
    "/sample-data/set2-hold/Set2_Impugned_DRC07_Order.pdf",
    "/sample-data/set2-hold/Set2_Statement_of_Facts_and_Grounds.txt"
]

print("=== CHECKING ASSET AVAILABILITY ON RENDER ===")
for ep in endpoints_to_check:
    try:
        req = urllib.request.Request(base_url + ep, headers={'User-Agent': 'Mozilla/5.0'})
        with urllib.request.urlopen(req) as res:
            print(f"[OK 200] {ep} ({res.length} bytes)")
    except Exception as e:
        print(f"[FAIL] {ep}: {e}")

# Run Live Test: Dataset 1 (Proceed Worthy - Retrospective Cancellation)
print("\n=== RUNNING LIVE EVALUATION: DATASET 1 (PROCEED WORTHY) ===")
with open("public/sample-data/set1-proceed/Set1_Statement_of_Facts_and_Grounds.txt", "r", encoding="utf-8") as f:
    set1_txt = f.read()

payload1 = {
    "title": "M/s Apex Precision Engineering - Retrospective NGTP Cancellation FY 2018-19",
    "taxpayerName": "Apex Precision Engineering Pvt. Ltd.",
    "gstin": "27AAACA9876C1Z3",
    "financialYear": "2018-19",
    "disputedAmount": "INR 38,40,000",
    "noticeType": "Order-in-Original / DRC-07",
    "primaryIssue": "Section 16(2)(c) ITC denial due to retrospective cancellation of supplier GSTIN even though tax was deposited via RTGS while registration was active",
    "caseSummary": set1_txt[:1500],
    "documents": [
        {"id": "d1", "name": "Set1_Tax_Invoice_Rule46.pdf", "type": "Invoice", "fileSize": "120 KB", "uploadedAt": "2024-04-10", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "Tax Invoice DMA/2018-19/0402 Hot Rolled Steel Coils 40 MT Tax 38,40,000 Supplier GSTIN 27AABCD5544E1Z2 was ACTIVE at invoice date."},
        {"id": "d2", "name": "Set1_Bank_RTGS_Statement.pdf", "type": "Bank Statement", "fileSize": "110 KB", "uploadedAt": "2024-04-10", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "RTGS DEBIT UTR HDFCR52018102400918234 amount 2,51,73,333 paid within 12 days while supplier registration was active"},
        {"id": "d3", "name": "Set1_EWay_Bill_PartA_B.pdf", "type": "E-Way Bill", "fileSize": "95 KB", "uploadedAt": "2024-04-10", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "E-Way Bill 241089201945 generated by supplier using ACTIVE GSTIN Vehicle MH-12-RN-7845 Part A and Part B valid"},
        {"id": "d4", "name": "Set1_Weighbridge_FASTag_Receipt.pdf", "type": "E-Way Bill", "fileSize": "105 KB", "uploadedAt": "2024-04-10", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "Weighbridge Slip DWB/18/10492 Net Weight 40040 Kg NHAI FASTag Toll Khalapur Kusgaon Talegaon continuous timestamps"},
        {"id": "d5", "name": "Set1_Tax_Ledger_GSTR1_Ack.pdf", "type": "Invoice", "fileSize": "90 KB", "uploadedAt": "2024-04-10", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "GSTR-1 ARN AA2710180918234 filed 10-11-2018 while registration ACTIVE."},
        {"id": "d6", "name": "Set1_Impugned_DRC07_Order.pdf", "type": "DRC-07", "fileSize": "115 KB", "uploadedAt": "2024-04-10", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "DRC-07 Order ZA2703240098412 disallowing ITC due to retrospective cancellation of supplier GSTIN ab initio"}
    ]
}

req1 = urllib.request.Request(f"{base_url}/api/analyze", data=json.dumps(payload1).encode('utf-8'), headers={'Content-Type': 'application/json'})
with urllib.request.urlopen(req1) as res:
    data1 = json.loads(res.read().decode('utf-8'))
    c1 = data1.get('evaluatedCase')
    print("-> SET 1 RECOMMENDATION:", c1['finalOutput']['executiveVerdict']['recommendation'])
    print("-> SET 1 READINESS SCORE:", c1['readinessScore']['totalScore'], "/ 100")
    print("-> SET 1 VIABILITY SCORE:", c1['viabilityScore']['totalScore'], "/ 100 (Probability:", c1['viabilityScore']['probabilityOfFavourableOutcome'] + ")")
    print("-> SET 1 GROUNDS COUNT:", len(c1.get('improvedSubmissions', [])))

# Run Live Test: Dataset 2 (Hold / Not Worthy)
print("\n=== RUNNING LIVE EVALUATION: DATASET 2 (NOT WORTHY / HOLD) ===")
with open("public/sample-data/set2-hold/Set2_Statement_of_Facts_and_Grounds.txt", "r", encoding="utf-8") as f:
    set2_txt = f.read()

payload2 = {
    "title": "M/s Shaurya Infra Projects - Paper-Only Circular Trading SCN",
    "taxpayerName": "Shaurya Infra Projects Ltd.",
    "gstin": "27AAACS4321D1Z8",
    "financialYear": "2019-20",
    "disputedAmount": "INR 52,00,000",
    "noticeType": "Order-in-Original / DRC-07",
    "primaryIssue": "Section 16(2)(c) circular trading allegation - NO e-way bill, NO transit proof, supplier fictitious 100 sq ft room, payment delayed 216 days beyond 180-day limit",
    "caseSummary": set2_txt[:1500],
    "documents": [
        {"id": "sd1", "name": "Set2_Tax_Invoice_Deficient.pdf", "type": "Invoice", "fileSize": "100 KB", "uploadedAt": "2024-04-15", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "Tax Invoice GTS/19-20/0118 building materials lump sum without vehicle or eway bill. Supplier Global Trading Syndicate fictitious entity 100 sq ft room"},
        {"id": "sd2", "name": "Set2_Bank_Statement_Delayed.pdf", "type": "Bank Statement", "fileSize": "100 KB", "uploadedAt": "2024-04-15", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "Paid after 216 days delayed beyond 180 days statutory limit under Section 16(2) Second Proviso. No reversal of credit done in interim."},
        {"id": "sd3", "name": "Set2_Impugned_DRC07_Order.pdf", "type": "DRC-07", "fileSize": "110 KB", "uploadedAt": "2024-04-15", "ocrReadability": "Clearly readable text", "extractedTextSnippet": "DRC-07 Order ZA2701240049182 circular trading without movement of goods under Section 74"}
    ]
}

req2 = urllib.request.Request(f"{base_url}/api/analyze", data=json.dumps(payload2).encode('utf-8'), headers={'Content-Type': 'application/json'})
with urllib.request.urlopen(req2) as res:
    data2 = json.loads(res.read().decode('utf-8'))
    c2 = data2.get('evaluatedCase')
    print("-> SET 2 RECOMMENDATION:", c2['finalOutput']['executiveVerdict']['recommendation'])
    print("-> SET 2 READINESS SCORE:", c2['readinessScore']['totalScore'], "/ 100")
    print("-> SET 2 VIABILITY SCORE:", c2['viabilityScore']['totalScore'], "/ 100 (Probability:", c2['viabilityScore']['probabilityOfFavourableOutcome'] + ")")
    print("-> SET 2 GROUNDS COUNT:", len(c2.get('improvedSubmissions', [])))